version: '3.7'
services:
  web-hugo:
    container_name: web-hugo
    image: jojomi/hugo:latest
    volumes:
      - ../:/src
      - ../docs/:/output
    #command: /bin/sh -c 'while true; do hugo --source="/src" --theme="curvytech" --destination="/output" --baseURL="" >/dev/null; sleep 5; done'
    #command: /bin/sh -c "while true; do sleep 5; done" 
    command: "/usr/local/sbin/hugo --watch=true --source=/src --theme=curvytech --destination=/output --baseURL=/"
    environment:
      - HUGO_WATCH=true
      - HUGO_REFRESH_TIME=-1
      - HUGO_THEME=curvytech
      - HUGO_BASEURL=/
#    restart: always

  web-nginx:
    container_name: web-nginx
    image: jojomi/nginx-static
    volumes:
      - ../docs:/var/www
    environment:
      - VIRTUAL_HOST=
    ports:
      - '1313:80'
#   restart: always
