# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "curvytech"
license = "MIT"
# licenselink = "https://github.com/jbarratt/serialized-hugo/blob/master/LICENSE.md"
description = "Custom theme for vitvar.com, based on Serialized theme from Joshua Barratt"
homepage = "https://vitvar.com"
tags = []
features = []
min_version = "0.20"

[author]
  name = "Tomas Vitvar"
  homepage = "https://vitvar.com"

[original]
  name = "Serialized"
  homepage = "https://serialized.net"
  repo = "https://github.com/jbarratt/serialized-hugo"
